@baseUrl = http://localhost:3000
@contentType = application/json

# --- VARIÁVEIS DE AMBIENTE (Preencha aqui para facilitar) ---
@email = santosray62@gmail.com
@password = Blessedhr10@

# Cole os tokens aqui após fazer o login para usar nas rotas protegidas
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMmRjM2M5Zi04N2JkLTQ3M2QtYjVhYy0zNzNhZjAyY2ZlZjkiLCJlbWFpbCI6InNhbnRvc3JheTYyQGdtYWlsLmNvbSIsInJvbGUiOiJNQVNURVIiLCJjb21wYW55SWQiOiIzMjhmNWYwOC1kOGEzLTQ2MzctYmJjYy1hOWQ1NmI2Zjg0NTYiLCJpYXQiOjE3NjY0Mzg5MDcsImV4cCI6MTc2NjQzOTgwN30.mMsg3kWcsfxCQ06AoGBVCHQ0_MG560Ojbc7j2etm2aI

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMmRjM2M5Zi04N2JkLTQ3M2QtYjVhYy0zNzNhZjAyY2ZlZjkiLCJlbWFpbCI6InNhbnRvc3JheTYyQGdtYWlsLmNvbSIsInJvbGUiOiJNQVNURVIiLCJjb21wYW55SWQiOiIzMjhmNWYwOC1kOGEzLTQ2MzctYmJjYy1hOWQ1NmI2Zjg0NTYiLCJpYXQiOjE3NjY0Mzg5MDcsImV4cCI6MTc2NzA0MzcwN30.kTzezer7j_ywRsLkaRILe8ZapHiY5xK1EiJzLGbhzOM


# ==============================================================================
# 1. AUTENTICAÇÃO (LOGIN)
# ==============================================================================

### Login - Sucesso
# Endpoint protegido por Throttle (Rate Limit)
# Retorna: accessToken (15min) e refreshToken (7dias)
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Login - Teste de Senha Errada
# Deve retornar 401 Unauthorized
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "{{email}}",
    "password": "senha_errada_123"
}


# ==============================================================================
# 2. PERFIL E DADOS (Rotas Protegidas)
# ==============================================================================

### Obter Perfil do Usuário
# Requer: Header Authorization com Access Token válido
# Validação: Passa pelo JwtAuthGuard e RolesGuard
GET {{baseUrl}}/auth/profile
Authorization: Bearer {{accessToken}}


# ==============================================================================
# 3. GESTÃO DE SESSÃO (Tokens)
# ==============================================================================

### Verificar Validade do Token
# Endpoint usado pelo Middleware do Next.js
# Verifica se o token ainda é válido e se o usuário está ATIVO no banco
POST {{baseUrl}}/auth/verify-token
Content-Type: {{contentType}}

{
    "token": "{{accessToken}}"
}

### Atualizar Tokens (Refresh)
# Usado quando o accessToken expira (401).
# Requer: Refresh Token válido no corpo.
# Retorna: Novo par de tokens.
POST {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}
Authorization: Bearer {{refreshToken}}

{
    "refreshToken": "{{refreshToken}}"
}


# ==============================================================================
# 4. TESTES DE SEGURANÇA E REGISTRO (Opcionais)
# ==============================================================================

### Tentar Acessar Perfil SEM Token
# Deve retornar 401 Unauthorized
GET {{baseUrl}}/auth/profile

### Tentar Acessar Perfil com Token Inválido/Expirado
# Deve retornar 401 Unauthorized
GET {{baseUrl}}/auth/profile
Authorization: Bearer token_falso_123456

