#==============================================
# 1. CRIAR UM NOVO USUÁRIO (MASTER ou ADMIN)
# Endpoint: POST /users
# Requer: MASTER/ADMIN Token
#==============================================
POST <URL_BASE>/users
Content-Type: application/json
Authorization: Bearer <COLOCAR_AQUI_SEU_ADMIN_JWT_TOKEN>

{
    "name": "Novo Empregado Teste",
    "email": "empregado.teste_novo@exemplo.com",
    "password": "SenhaSegura123",
    "role": "EMPLOYER",
    "document": "99988877700",
    "contact": "99999999999",
    "professionalRole": "Operador de Máquina",
    "companyId": "<COLOCAR_AQUI_ID_DA_EMPRESA>"
}


#==============================================
# 2. LISTAR TODOS OS USUÁRIOS (MASTER ou ADMIN)
# Endpoint: GET /users
# Requer: MASTER/ADMIN Token
# Filtros: Adicione filtros na URL.
#==============================================
GET <URL_BASE>/users?limit=2&companyId=<COLOCAR_AQUI_ID_DA_EMPRESA>
Authorization: Bearer <COLOCAR_AQUI_SEU_MASTER_JWT_TOKEN>


#==============================================
# 3. BUSCAR USUÁRIO POR ID
# Endpoint: GET /users/:id
# Requer: Qualquer Token Logado
#==============================================
GET <URL_BASE>/users/<COLOCAR_AQUI_ID_DO_USUARIO_PARA_TESTE>
Authorization: Bearer <COLOCAR_AQUI_SEU_ADMIN_JWT_TOKEN>


#==============================================
# 4. BUSCAR USUÁRIOS POR QUERY (Search)
# Endpoint: GET /users/search
# Requer: Qualquer Token Logado
#==============================================
GET <URL_BASE>/users/search?query=Empregado&companyId=<COLOCAR_AQUI_ID_DA_EMPRESA>
Authorization: Bearer <COLOCAR_AQUI_SEU_ADMIN_JWT_TOKEN>


#==============================================
# 5. ATUALIZAR USUÁRIO (MASTER ou ADMIN)
# Endpoint: PATCH /users/:id
# Requer: MASTER/ADMIN Token
#==============================================
PATCH <URL_BASE>/users/<COLOCAR_AQUI_ID_DO_USUARIO_PARA_TESTE>
Content-Type: application/json
Authorization: Bearer <COLOCAR_AQUI_SEU_ADMIN_JWT_TOKEN>

{
    "name": "Empregado Nome Atualizado",
    "professionalRole": "Gerente de Produção",
    "password": "NovaSenhaForte456"
}


#==============================================
# 6. ALTERNAR STATUS DO USUÁRIO PARA INACTIVE
# Endpoint: PATCH /users/:id/status/INACTIVE
# Requer: MASTER/ADMIN Token
#==============================================
PATCH <URL_BASE>/users/<COLOCAR_AQUI_ID_DO_USUARIO_PARA_TESTE>/status/INACTIVE
Authorization: Bearer <COLOCAR_AQUI_SEU_ADMIN_JWT_TOKEN>


#==============================================
# 7. ALTERNAR STATUS DO USUÁRIO DE VOLTA PARA ACTIVE
# Endpoint: PATCH /users/:id/status/ACTIVE
# Requer: MASTER/ADMIN Token
#==============================================
PATCH <URL_BASE>/users/<COLOCAR_AQUI_ID_DO_USUARIO_PARA_TESTE>/status/ACTIVE
Authorization: Bearer <COLOCAR_AQUI_SEU_ADMIN_JWT_TOKEN>


#==============================================
# 8. REMOVER USUÁRIO (APENAS MASTER)
# Endpoint: DELETE /users/:id
# Requer: MASTER Token
# ATENÇÃO: Esta é uma exclusão física!
#==============================================
DELETE <URL_BASE>/users/<COLOCAR_AQUI_ID_DO_USUARIO_PARA_TESTE>
Authorization: Bearer <COLOCAR_AQUI_SEU_MASTER_JWT_TOKEN>