### Base URL
@baseUrl = http://localhost:3000
@contentType = application/json

### 1. Criar usuário
POST {{baseUrl}}/auth/signup
Content-Type: {{contentType}}

{
  "id": "418bd1d6-35b6-47dc-8e7b-319243e42a0d",
  "email": "santosray62@gmail.com",
  "password": "Blessedhr10",
  "name": "Highlander",
  "companyId": "6cc6fafe-ed27-4000-8780-8623b8859bc5",
  "role": "USER",
  "contact": "85985645360"
}

### LOGIN - Usuário válido
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "santosray62@gmail.com",
  "password": "Blessedhr10"
}
