### Variáveis Globais
@baseUrl = http://localhost:3000
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMmRjM2M5Zi04N2JkLTQ3M2QtYjVhYy0zNzNhZjAyY2ZlZjkiLCJlbWFpbCI6InNhbnRvc3JheTYyQGdtYWlsLmNvbSIsInJvbGUiOiJNQVNURVIiLCJjb21wYW55SWQiOiIzMjhmNWYwOC1kOGEzLTQ2MzctYmJjYy1hOWQ1NmI2Zjg0NTYiLCJpYXQiOjE3Njk2MjUyNjUsImV4cCI6MTc2OTYyNjE2NX0.i6XrmB-P8a7iBql0_QcNcHrwoJmgEl3ydXACSXojSwA

# Cole o ID de um material aqui para testar GET One, PATCH e DELETE
@materialId = 363cd8ab-10e8-4881-89b8-1fdfd52c72a9

### -------------------------------------------------------
### 1. CRIAR MATERIAL (Tecido)
### -------------------------------------------------------
POST {{baseUrl}}/materials
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "name": "Malha Penteada 30.21",
  "type": "Tecido21",
  "description": "Algodão 100% de alta qualidade21",
  "color": "Branco21",
  "unitOfMeasure": "KG",
  "yieldPerKg": 5
}

### -------------------------------------------------------
### 2. CRIAR MATERIAL (Aviamento/Outro Exemplo)
### -------------------------------------------------------
POST {{baseUrl}}/materials
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "name": "Botão de Madeira 16mm",
  "type": "Aviamento1",
  "description": "Botão rústico para camisaria1",
  "color": "Madeira1",
  "unitOfMeasure": "UN",
  "yieldPerKg": 0
}

### -------------------------------------------------------
### 3. LISTAR TODOS (Padrão)
### -------------------------------------------------------
GET {{baseUrl}}/materials
Authorization: Bearer {{token}}

### -------------------------------------------------------
### 4. LISTAR COM PAGINAÇÃO E BUSCA
### -------------------------------------------------------
# Busca por "Malha", página 1, 5 itens por página
GET {{baseUrl}}/materials?page=1&limit=5&search=Tecido21
Authorization: Bearer {{token}}

### -------------------------------------------------------
### 5. BUSCAR UM ÚNICO MATERIAL (Pelo ID)
### -------------------------------------------------------
GET {{baseUrl}}/materials/{{materialId}}
Authorization: Bearer {{token}}

### -------------------------------------------------------
### 6. ATUALIZAR MATERIAL (Patch - Parcial)
### -------------------------------------------------------
PATCH {{baseUrl}}/materials/{{materialId}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "color": "Off-White1",
  "description": "Atualizado: Algodão egípcio1",
  "yieldPerKg": 50
}

### -------------------------------------------------------
### 7. DELETAR MATERIAL (Soft Delete)
### -------------------------------------------------------
DELETE {{baseUrl}}/materials/{{materialId}}
Authorization: Bearer {{token}}